name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check AWS CLI version
        run: aws --version

      - name: Set up AWS CLI
        run: |
          echo "Setting up AWS credentials"
          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          export AWS_REGION="us-east-1"  # Change to your region if needed

          # Configure AWS CLI
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/config
          echo "region = $AWS_REGION" >> ~/.aws/config
          echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
          echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials

      - name: Upload files to S3
        run: |
          # Export credentials again in this step
          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          export AWS_REGION="us-west-1"
          
          # Upload files to S3
          aws s3 cp index.html s3://np-cloud-resume/index.html --acl public-read
          aws s3 cp style.css s3://np-cloud-resume/style.css --acl public-read
          aws s3 cp script.js s3://np-cloud-resume/script.js --acl public-read
